### ISSUE TITLE
Rare ISR error in follow_hardware_timing mode

### ISSUE THREAD

**Issue by tom-f-oconnell** [tom-f-oconnell/olfactometer#3]
This indicates that there the ISR error I thought might never be triggered can happen at least in some cases. May thus be worth rewriting that portion of the firmware to have less assumptions, a shorter ISR, etc.

Contents of `3trials_6odors_inorder.yaml`:
```
settings:
  follow_hardware_timing: true
  enable_timing_output: true

pin_sequence:
  # The rows in this bulleted list happen one after the other.
  pin_groups:
  # The pins listed in each of these rows will all be concurrently 
  # switched ONCE
  - pins: [2]
  - pins: [2]
  - pins: [2]
  - pins: [3]
  - pins: [3]
  - pins: [3]
  - pins: [4]
  - pins: [4]
  - pins: [4]
  - pins: [5]
  - pins: [5]
  - pins: [5]
  - pins: [6]
  - pins: [6]
  - pins: [6]
  - pins: [7]
  - pins: [7]
  - pins: [7]

# Other available pins we aren't using.
#  - pins: [8]
#  - pins: [9]
#  - pins: [10]
#  - pins: [11]
#  (pin 12 corresponded to a broken valve on this olfactometer, which is
#  plugged, as it failed open)
```

Error message (main thing is just that the `ISR error!` print was triggered. I think I manually `Ctrl-C`-ed this run, and I'm not now sure if I saw the error print before or after doing so):
```
(venv) tom@ace:~/2020-08-17_eag_stimuli$ olf -u 3trials_6odors_inorder.yaml
nanopb_generator --output-dir=/tmp/tmpv_5khs11/olfactometer -I /home/tom/src/olfactometer/venv/lib/  python3.6/site-packages/olfactometer /home/tom/src/olfactometer/venv/lib/python3.6/site-packages/    olfactometer/olf.proto
Writing to /tmp/tmpv_5khs11/olfactometer/olf.pb.h and /tmp/tmpv_5khs11/olfactometer/olf.pb.c
Detected an arduino:avr:mega on port /dev/ttyACM0
arduino-cli compile -b arduino:avr:mega /tmp/tmpv_5khs11/olfactometer --libraries /tmp/tmpv_5khs11/  libraries --build-path /tmp/tmpv_5khs11/build --build-cache-path /tmp/tmpv_5khs11/build-cache -u -t -p /dev/ttyACM0
Sketch uses 14336 bytes (5%) of program storage space. Maximum is 253952 bytes.
Global variables use 2500 bytes (30%) of dynamic memory, leaving 5692 bytes for local variables.     Maximum is 8192 bytes.
Baud rate (parsed from Arduino sketch): 115200
Connected
Ready (waiting for hardware triggers)
ISR error!
^CTraceback (most recent call last):
  File "/home/tom/src/olfactometer/venv/bin/olf", line 47, in <module>
    try_parse=try_parse, verbose=verbose
  File "/home/tom/src/olfactometer/venv/lib/python3.6/site-packages/olfactometer/util.py", line 574, in main
    line = ser.readline()
  File "/home/tom/src/olfactometer/venv/lib/python3.6/site-packages/serial/serialposix.py", line     483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt
```

This happened in a run with a development install on my Ubuntu 16.04 laptop.  The version was `27983fd9a` *plus* some uncommitted changes to the firmware to avoid a reset so soon after the last pulse (It was a hardcoded `delay` of several seconds at the end, I believe. This delay may have been committed at some point shortly after, though I believe it is removed now).

Command used to run the experiment (from `~/2020-08-17_eag_stimuli`):
```
olf 3trials_6odors_inorder.yaml
```

Most runs the same day did not have this issue, which I think I only experienced once.
