### ISSUE TITLE
Arduino version string not read correctly (cause unclear)

### ISSUE THREAD

**Issue by tom-f-oconnell** [tom-f-oconnell/olfactometer#5]
Error:
```
(venv) tom@ace:~/src/tom_olfactometer_configs$ olf -u test_pair_conc_grid.yaml 
Using the 'pair_concentration_grid' generator configured with test_pair_conc_grid.yaml
Writing generated YAML under ./20201125_151124_stimuli/

Config file: 20201125_151124_stimuli/20201125_151124_stimuli_0.yaml (1/2)
nanopb_generator --output-dir=/tmp/tmptfkhkpva/olfactometer -I /home/tom/src/olfactometer/venv/lib/python3.6/site-packages/olfactometer /home/tom/src/olfactometer/venv/lib/python3.6/site-packages/olfactometer/olf.proto
Writing to /tmp/tmptfkhkpva/olfactometer/olf.pb.h and /tmp/tmptfkhkpva/olfactometer/olf.pb.c
Detected an arduino:avr:mega on port /dev/ttyACM0
arduino-cli compile -b arduino:avr:mega /tmp/tmptfkhkpva/olfactometer --libraries /tmp/tmptfkhkpva/libraries --build-path /tmp/tmptfkhkpva/build --build-cache-path /tmp/tmptfkhkpva/build-cache --build-properties build.extra_flags="-DOLFACTOMETER_VERSION_STR=5f5c6f3b5d6b0dc552401c0b87450e07a901d495" -u -t -p /dev/ttyACM0
Sketch uses 14552 bytes (5%) of program storage space. Maximum is 253952 bytes.
Global variables use 1609 bytes (19%) of dynamic memory, leaving 6583 bytes for local variables. Maximum is 8192 bytes.
Baud rate (parsed from Arduino sketch): 115200
Pins to connect odors to:
 2: solvent for ethyl hexanoate
 3: ethyl hexanoate @ -3
 9: 1-hexanol @ -3
 10: solvent for 1-hexanol
Press Enter once the odors are connected
Connected
Traceback (most recent call last):
  File "/home/tom/src/olfactometer/venv/bin/olf", line 62, in <module>
    ignore_ack=ignore_ack, try_parse=try_parse, verbose=verbose
  File "/home/tom/src/olfactometer/venv/lib/python3.6/site-packages/olfactometer/util.py", line 990, in main
    run(config_file, _first_run=first_run, **kwargs)
  File "/home/tom/src/olfactometer/venv/lib/python3.6/site-packages/olfactometer/util.py", line 894, in run
    if arduino_version_str == upload.no_clean_hash_str:
UnboundLocalError: local variable 'arduino_version_str' referenced before assignment
```

Input:
```
available_group1_valve_pins: [2, 3, 4, 5]
available_group2_valve_pins: [8, 9, 10, 11]
group1_balance_pin: 7
group2_balance_pin: 12

recording_indicator_pin: 20
timing_output_pin: 21

n_trials: 1
randomize_pair_order: True
randomize_first_ramped_odor: True
randomize_pairs_to_manifolds: True

global_log10_concentrations: [-3]

odor_pairs:
  - pair:
    - ethyl hexanoate
    - 1-hexanol
    reason: high joint
  - pair:
    - butanal
    - acetone
    reason: high PMI

pre_pulse_s: 2
pulse_s: 4
post_pulse_s: 3

generator: pair_concentration_grid
```

After seemingly having success with the same / similar tests on my 18.04 desktop (just before pushing the relevant commit) (though maybe I didn't actually go through any of the parts  that required the Arduino? I thought I did...), I pulled `5f5c6f3b5` of my olfactometer repo and `51ad32767` of `tom_olfactometer_configs` on my 16.04 laptop, and encountered this with the same Arduino Mega now connected to my laptop.

Unclear if the Arduino somehow sent an empty line, or if an empty string is the default of some read operation when no input, or if there was perhaps some other communication error, or something else entirely. Either way, I should better avoid the possibility of having this variable undefined. At least should have some more descriptive error message.
